### ISSUE TITLE
OpenStack Controller thinks there are 4 nodes when there are only 2...

### ISSUE THREAD

**Issue by chrismarino** [romana/romana#10]
Something is not reset in the installation scripts. I launched a cluster with 1 Compute, 1 Controller. Then changed the conf to build with 3 Compute. That all worked. Then I changed it back to 1 Compute. The cluster launched properely, but their are routes on the Controller to Compute Nodes that don't exist.

    ubuntu@ip-192-168-0-10:~$ route -n
    Kernel IP routing table
    Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
    0.0.0.0         192.168.0.1     0.0.0.0         UG    0      0        0 eth0
    10.0.0.0        0.0.0.0         255.255.0.0     U     0      0        0 romana-gw
    10.1.0.0        192.168.0.11    255.255.0.0     UG    0      0        0 eth0
    10.2.0.0        192.168.0.12    255.255.0.0     UG    0      0        0 eth0
    10.3.0.0        192.168.0.13    255.255.0.0     UG    0      0        0 eth0
    10.4.0.0        192.168.0.14    255.255.0.0     UG    0      0        0 eth0
    192.168.0.0     0.0.0.0         255.255.255.0   U     0      0        0 eth0
    192.168.122.0   0.0.0.0         255.255.255.0   U     0      0        0 virbr0

**Comment by cgilmour** [comment]
The latest installer is better about this behaviour. You'll only see the hosts/IPs/routes that were chosen at install time.
