### ISSUE TITLE
Failing on ssh timeout

### ISSUE THREAD

**Issue by flashvoid** [romana/romana#11]
EC2 instances are not always immediately available after SSH port open. You're trying to log in right after ssh opens but it might fail on timeout.

Need ping loop
``` 
for i in $(seq 1 10); do 
        ansible -i ec2.py -m ping all && break
        sleep 10
done
```

**Comment by cgilmour** [comment]
Latest installer uses this approach for ensuring hosts can be reached and the rest of the ansible steps can be executed.

https://github.com/romana/romana/blob/491e337be5fbd0516638cebecbf872e8103fc3ad/romana-install/romana-setup#L164-L178
