### ISSUE TITLE
fail agent

### ISSUE THREAD

**Issue by neegor** [romana/romana#173]
Romana v.2
Kubeadm
Kubernetes 1.7.5

```
{"log":"2017-09-14T09:00:39Z ERROR    : Block {1 {{10.112.0.0 fffffff8}} tenant  kube-master 1} is local and does not require a route on that host\n","stream":"stderr","time":"2017-09-14T09:00:39.174484023Z"}
```
Thanks

**Comment by flashvoid** [comment]
Hello @neegor 
The message you are getting isn't really an error, it just means system skips one route because it exists implicitly as `connected`.

We will probably switch it into `DEBUG` level for next release. Please don't worry about it.
