### ISSUE TITLE
Agents complaining about context deadline exceeded

### ISSUE THREAD

**Issue by ebauman** [romana/romana#178]
Greetings,

I am running k8s 1.9 / romana 2.0.2 (recently upgraded from 2.0.1 as an attempt to fix this issue). 
Every romana-agent instance has the following entries in its logs:

`Failed to update ipsets, can't apply Romana policies, context deadline exceeded`

This is coupled with an inability to setup romana VIPs.
It appears containers still receive IPs appropriately though.

**Comment by chrismarino** [comment]
Hi @ebauman can you describe more completely when this happened? When you installed? When you tried to create a Romana VIP? Or add a Network Policy?

**Comment by ebauman** [comment]
Sure thing, sorry for the lack of detail.

This morning I attempted to deploy a service to my new k8s cluster. 
I had previously installed k8s 1.9 / romana 2.0.1 a few weeks ago. At that time I did some simple testing with an nginx pod and service and was able to assign a VIP from the subnet that my hosts were on. 

Today when I attempted to deploy this service, the service did not receive a VIP from romana.

That's when I dug into the logs on the agent containers and saw the aforementioned entries.

**Comment by pritesh** [comment]
@ebauman can you please paste the annotation use for romanaVIP here?

**Comment by ebauman** [comment]
```
apiVersion: v1
kind: Service
metadata:
  name: vault
  annotations:
    romanavip: '{"auto": false, "ip": "1.2.3.4"}'
```

**Comment by chrismarino** [comment]
@ebauman send an email to info@romana.io and we can take this to slack, if you want.

**Comment by ebauman** [comment]
Will do! I'll follow-up shortly. Thanks @chrismarino
