### ISSUE TITLE
http://docs.romana.io/ - do not work

### ISSUE THREAD

**Issue by phozzy** [romana/romana#186]
attempt to open http://docs.romana.io/ gives next error:
```
403 Forbidden

    Code: AllAccessDisabled
    Message: All access to this object has been disabled
    RequestId: 9D0BAC3B14F370D5
    HostId: VvORaqgUfQvTj+F7RcsLW6Y2jafRW7HVD2rUKopLyoGHZi3yplqXbksIQZmHy5gF8q5WQm5Kvf8=
```

**Comment by chrismarino** [comment]
Sorry about that. The link is broken. The docs were moved to http://romana.readthedocs.io

**Comment by phozzy** [comment]
https://github.com/romana/romana/pull/187

**Comment by phozzy** [comment]
Great! Now it is better :-) I am closing this issue.
