### ISSUE TITLE
Enable etcd TLS connection

### ISSUE THREAD

**Issue by scruplelesswizard** [romana/romana#189]
From reading the code (the docs certainly need to be improved in this regard) it appears that it is not possible to provide a client certificate for Romana to access the etcd cluster where it stores it's configuration.

Am I missing some configuration somewhere that allows using a client certificate to access the etcd cluster?

**Comment by chrismarino** [comment]
Pretty sure you are correct. Several TLS capabilities have not been implemented yet. @cgilmour would know for sure...

**Comment by rolindroy** [comment]
Any update on this issue ? We're facing the same.

**Comment by scruplelesswizard** [comment]
We changed to use alternatives as it seems Romana is not actively maintained, and other CNI providers offered all our required feature sets. I would strongly suggest you do the same @rolindroy
