### ISSUE TITLE
Get different traceroute results on different segments...

### ISSUE THREAD

**Issue by chrismarino** [romana/romana#62]
Just launched a 6.2 cluster (not master). Installed fine. Had some weirdness with a VM getting 2 IPs, and no tap interfaces. Killed the instances and tried again. Second time it all seemed to work.

Then did a traceroute and the intermediate hop showed up in the path! Did not expect that. Tried from a different instance on the other segment and got the * * * as I expected.

Will leave the cluster running at http://54.183.215.241/

Not going to fuss with this right now. I got the output Ineeded for the page I'm updating

**Comment by cgilmour** [comment]
I think this has been addressed. Traceroute inconsistency was sorted a while ago, and bug fixes to the installer have been applied for avoiding virbr0 creation.
