### ISSUE TITLE
README additions, group_vars/all confusion....

### ISSUE THREAD

**Issue by chrismarino** [romana/romana#8]
The README should be more explicit about the options that can be set in the 'group_vars/all' file.

Seems that the devstack user name can be set as an option, but does the file need to be edited to change the other values?  Presume, yes.

There should be other examples in there to show what can be set. The number of nodes, for example is something I think a lot of people will be interested in changing. 

Also, the key_name is 'shared-key-1' Is that correct?  that's what I had at first and the install broke. It expected 'ec2_id_rsa' someplace else? Kinda confusing...

**Comment by cgilmour** [comment]
Big changes in group_vars in the updated installer.
I don't think users should be playing with the values in there -- it's very "at your own risk".

We could wait for a bit more community feedback about what things they actually want to change, and find the best way to provide it.
